name: golang-library
files:
  - '*.*'
  - '.*'
  - '*'
  - '__tests__/*.go'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /pkgjson-description/g
    to: "Interactive Pipe To: The golang cli interactive workflow."
  - from: /pkgjson/g
    to: ${PROJECT_NAME}
  - from: /pkgname/g
    to: ipt
